version: "3"
services:
  app:
    build: .
    restart: always
    depends_on:
      - database
    environment:
      PORT: 3000
      DB_HOST: database
      DB_PORT: 5432
      DB_USER: test
      DB_PASS: test
      DB_NAME: test
    ports:
      - "${PORT}:3000"
  database:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: test
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
      POSTGRES_PORT: 5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
volumes:
  postgres-data: {}
